# CustomizationUnknownFailure

The customization sequence failed unexpectedly in the guest.  ***Since:*** VI API 2.5 

## Properties
Name | Type | Description | Notes
------------ | ------------- | ------------- | -------------

## Example

```python
from vmware_vi.models.customization_unknown_failure import CustomizationUnknownFailure

# TODO update the JSON string below
json = "{}"
# create an instance of CustomizationUnknownFailure from a JSON string
customization_unknown_failure_instance = CustomizationUnknownFailure.from_json(json)
# print the JSON string representation of the object
print CustomizationUnknownFailure.to_json()

# convert the object into a dict
customization_unknown_failure_dict = customization_unknown_failure_instance.to_dict()
# create an instance of CustomizationUnknownFailure from a dict
customization_unknown_failure_form_dict = customization_unknown_failure.from_dict(customization_unknown_failure_dict)
```
[[Back to Model list]](../README.md#documentation-for-models) [[Back to API list]](../README.md#documentation-for-api-endpoints) [[Back to README]](../README.md)


